version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: product-db
      POSTGRES_USER: local-user
      POSTGRES_PASSWORD: local-password